# Generated by Django 4.0.3 on 2022-03-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('position', models.IntegerField(choices=[(1, 'Генеральный директор'), (2, 'Рководитель отдела'), (3, 'Руководитель подразделения'), (4, 'Менеджер'), (5, 'Продавец')], verbose_name='Должность')),
                ('date', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер заработной платы')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Информация о выплаченной зарплате')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
