# Generated by Django 4.0.3 on 2022-04-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='parent',
            new_name='сhief',
        ),
        migrations.RemoveField(
            model_name='table',
            name='date_added',
        ),
    ]
